services: mongodb
language: node_js
node_js:
- '0.11'
- '0.10'
before_install: npm install -g grunt-cli
deploy:
  provider: appfog
  email: boyan@rabchev.com
  skip_cleanup: true
  password:
    secure: JvuXFBJok9iTldyP6FZRCnlRGtTcVgZIaTfnqp1qfLOuwzzeADVvmjPxQCyjgzYCCH+NT3uiZVq51gquO7WwC7pu5L4rTqSWuWOfB+larxm/CL0Vt2CMFWEgOubyoTuMUU/pF/Bg46eOzof2k7CUcmbhZlVicFD1XXk5O8AKd2w=
  app:
    master: ilg-dev
    production: ilg
  on:
    tags: true
    repo: rabchev/ilg-site
